#! /usr/bin/perl -w
# $Id: mkwords,102,v 1.1 2003/05/15 21:14:45 ds Exp $

my %words;
my %seen;
my @codes;
my $i;

sub mycmp ($$)
{
  my $A = shift; $A = ${$A}[1];
  my $B = shift; $B = ${$B}[1];
  return (index ($B, $A) == 0) ? 1 : ($A cmp $B);
}

while (<>)
{
  chomp;
  next if $_ eq '' || $_ =~ /^;/o;
  /^(.)(.)(.*)$/;
  my $k = $2 | ' ';
  my $word = $2.$3;
  push @{$words{$k}}, [$1, $word] unless defined $seen{$word};
  $seen{$word} = 1;
}

my @keys = sort keys %words;

for $i (@keys)
{
  @{$words{$i}} = sort { mycmp ($a, $b) } @{$words{$i}};
}

for $i (@keys)
{
  my $j;
  my @w = @{$words{$i}};
  for ($j = 0; $j < @w; $j++)
  {
    printf "	=	\"%s\",	\" %s\"\n", $w[$j][1], $w[$j][0];
  }
}

print "\n	END\n";
exit 0;
